apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: telegraf
  ports:
    - protocol: TCP
      port: 8125
      targetPort: 8125
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  replicas: 1
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf_img
          imagePullPolicy: Never
          ports:
            - containerPort: 8125